a, b =input().split()
c = int(a) + int(b)
d = int(a) - int(b)
e = int(a) * int(b)
f = int(a) // int(b)
g = int(a) % int(b)
h = int(a) / int(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print("{:.2f}".format(h))